#!/bin/bash

echo "🌐 FREE HOSTING WITH CUSTOM DOMAIN SUPPORT"
echo "==========================================="
echo ""
echo "🎯 BEST OPTIONS FOR onelastai.com:"
echo ""
echo "🥇 RENDER (RECOMMENDED)"
echo "----------------------"
echo "✅ FREE tier with custom domain"
echo "✅ Rails auto-deployment"
echo "✅ Free SSL certificates"
echo "✅ MongoDB support"
echo "✅ Easy DNS setup"
echo "🔗 https://render.com"
echo ""
echo "🥈 RAILWAY (Paid but cheap)"
echo "---------------------------"
echo "✅ $5/month for custom domain"
echo "✅ Excellent Rails support"
echo "✅ MongoDB included"
echo "✅ Auto SSL"
echo "🔗 https://railway.app"
echo ""
echo "🥉 FLY.IO"
echo "----------"
echo "✅ Free allowance"
echo "✅ Custom domains"
echo "✅ Global deployment"
echo "✅ Rails support"
echo "🔗 https://fly.io"
echo ""
echo "🥉 NETLIFY + BACKEND"
echo "--------------------"
echo "✅ Free tier"
echo "✅ Custom domain"
echo "✅ Need separate backend service"
echo "🔗 https://netlify.com"
echo ""
echo "💡 RECOMMENDATION: RENDER"
echo "========================="
echo "✅ 100% FREE with custom domain"
echo "✅ Perfect for Rails + MongoDB"
echo "✅ onelastai.com will work!"
echo "✅ 5-minute setup"
echo ""
echo "🚀 SHALL WE GO WITH RENDER?"
