version: '3.8'

services:
  # Single Ollama service exposing one API; select model by name in requests
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    volumes:
      - ollama_data:/root/.ollama
    command: |
      bash -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama3.2:3b &&
        ollama pull mistral:7b &&
        ollama pull deepseek-coder:6.7b &&
        ollama pull phi3:14b || true &&
        ollama pull qwen2.5:7b-instruct || true &&
        ollama pull mistral-nemo:12b-instruct || true &&
        ollama pull nomic-embed-text || true &&
        wait"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    driver: local
