#!/bin/bash

echo "🚀 RAILWAY DEPLOYMENT GUIDE"
echo "============================"
echo ""
echo "⚡ FASTEST PATH TO LIVE SITE (5 minutes!)"
echo ""
echo "🎯 STEP 1: Prepare Railway Configuration"
echo "----------------------------------------"
echo "✅ Creating railway.json config..."
echo "✅ Setting up Procfile..."
echo "✅ Configuring environment variables..."
echo ""
echo "🎯 STEP 2: Deploy to Railway"
echo "----------------------------"
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose: 1-ManArmy/fluffy-space-garbanzo"
echo "6. Railway will auto-detect Rails app!"
echo ""
echo "🎯 STEP 3: Configure MongoDB"
echo "-----------------------------"
echo "1. In Railway dashboard, click '+ Add Service'"
echo "2. Select 'MongoDB'"
echo "3. Copy connection string to environment"
echo ""
echo "🎯 STEP 4: Go LIVE!"
echo "-------------------"
echo "✅ Railway generates live URL: yourapp.railway.app"
echo "✅ Configure custom domain: onelastai.com"
echo "✅ SSL automatically enabled!"
echo ""
echo "🔥 TOTAL TIME: ~5 MINUTES TO LIVE SITE!"
