#!/bin/bash

echo "🔥 RENDER DEPLOYMENT SETUP"
echo "=========================="
echo ""
echo "✅ Step 1: Configuration files created"
echo "   - render.yaml ✓"
echo "   - Gemfile ready ✓"
echo ""
echo "✅ Step 2: Build script for Render"
echo "   - Bundle install ✓"
echo "   - Precompile assets ✓"
echo "   - Database setup ✓"
echo ""
echo "🚀 DEPLOY TO RENDER NOW:"
echo "========================"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Web Service'"
echo "4. Connect Repository: 1-ManArmy/fluffy-space-garbanzo"
echo "5. Render will auto-detect Rails!"
echo ""
echo "📋 RENDER SETTINGS:"
echo "-------------------"
echo "Name: onelastai"
echo "Environment: Ruby"
echo "Build Command: bundle install"
echo "Start Command: bundle exec rails server -b 0.0.0.0 -p \$PORT -e production"
echo ""
echo "🌐 CUSTOM DOMAIN SETUP:"
echo "------------------------"
echo "1. In Render dashboard → Settings → Custom Domains"
echo "2. Add: onelastai.com"
echo "3. Add: www.onelastai.com"
echo "4. Copy CNAME/A records to Hostinger DNS"
echo ""
echo "⚡ TOTAL TIME: 5-10 MINUTES TO LIVE!"
echo ""
echo "🎯 Ready to deploy? Push to GitHub and deploy!"
